application: caretplanner
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /style
  static_dir: style
  
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: main.py
