application: caretplanner
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /oauth2callback
  script: oauth2client/appengine.py

- url: /style
  static_dir: style
  
- url: /img
  static_dir: img

- url: /.*
  script: main.py
